#yaml script to clean up the branches that are merged - Github Actions

name: Cleanup merged Yaml

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkoutv@2

      - name: Deleted merged branches
        run: |
          git fetch --prune
          git branch --merged main | grep -v "main" | xargs git branch -d

